In [2]:
import numpy as np
import pandas as pd

In [3]:
Data={'Names':['Ramesh','Suresh','Satish',np.nan],
      'Age':[np.nan,22,25,27],
      'City':['Pune','Pune',np.nan,'Hyd']}

df=pd.DataFrame(Data)
df
# Note here np.nan is a missing values of the dataframe

Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   NaN
3     NaN  27.0   Hyd

In [12]:
Data={'Names':['Ramesh','Suresh','Satish',None],
      'Age':[None,22,25,27],
      'City':['Pune','Pune',None,'Hyd']}

df1=pd.DataFrame(Data)
df1

# so here if we mention None instead of np.nan 
# to bhi koie problem nahi hai

Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0  None
3    None  27.0   Hyd

In [21]:
Data={'Names':['Ramesh','Suresh','Satish',Null],
      'Age':[Null,22,25,27],
      'City':['Pune','Pune',Null,'Hyd']}

df2=pd.DataFrame(Data)
df2

# Here if I mention Null then it will show error beacuse Null is in black colour

NameError: name 'Null' is not defined

In [13]:
# Now save the dataframe and see the file

Data={'Names':['Ramesh','Suresh','Satish',np.nan],
      'Age':[np.nan,22,25,27],
      'City':['Pune','Pune',np.nan,'Hyd']}
 
df=pd.DataFrame(Data)


df.to_csv('none_dataframe.csv',index=False)

In [14]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

In [15]:
df.isnull

<bound method DataFrame.isnull of     Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   NaN
3     NaN  27.0   Hyd>

In [16]:
df.isnull()

Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [17]:
df.isnull().sum()
# here .sum() is telling about how many null values are avaliable in df dftarame
# so in names column 1 null value is avaliable and in age column there is 1 null value etc

Names    1
Age      1
City     1
dtype: int64

## fillina

- This is the one method which helps to fill null values

In [18]:
df.fillna(30)
# iss method se pure column ki null value fill ho jayange
# but if we want to fill sspecific column null value use that column name

Names   Age  City
0  Ramesh  30.0  Pune
1  Suresh  22.0  Pune
2  Satish  25.0    30
3      30  27.0   Hyd

In [22]:
df['City'].fillna(25)

0    Pune
1    Pune
2      25
3     Hyd
Name: City, dtype: object

In [23]:
df['Age'].fillna(11)

0    11.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [24]:
df
# So here humane null value fill kar di lakin fir bhi vo output mai nahi dika 
# iska reason yaha hai ki humane inplace=true nahi kiya hai 
# agar vo karte to values save ho jati and output me bhi aa jati

Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   NaN
3     NaN  27.0   Hyd

In [26]:
df.fillna('hyd')

Names   Age  City
0  Ramesh   hyd  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   hyd
3     hyd  27.0   Hyd

- The above one is we are filling randomly

- all the columns are filled with random numbers

- It is not a good apporach beacuse in data we have different data types

**What is the difference between np.nan and none**

In [12]:
np.nan+5

nan

In [13]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

## Array

- We will learn array in numpy right now just read it

In [14]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,None,3])
# note when we use .array then our dataframes convert into array

In [15]:
arr1

array([ 1.,  2., nan,  3.])

In [16]:
arr2

array([1, 2, None, 3], dtype=object)

In [17]:
np.nansum(arr1),np.sum(arr1)

(np.float64(6.0), np.float64(nan))

In [18]:
np.sum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

- np.nap represents **float type**

- None represents **Object Tupe**

- if data operations related to maths then nan format is better



## Fill the value Based on specific column

In [19]:
# df.fillna()

df['Names'].fillna('Manish')

0    Ramesh
1    Suresh
2    Satish
3    Manish
Name: Names, dtype: object

## Fill with methods

- Here we have somes methods of fillna

- Whenever we are using methods no need to provide values

- pad

- bfill

- ffill

- backfill

In [1]:
import numpy as np
import pandas as pd

In [4]:
df.fillna(method='pad')

# C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1904\196241153.py:1: FutureWarning: DataFrame.
# fillna with 'method' is deprecated and will raise in a future version.Use obj.ffill() or obj.bfill() instead.
# df.fillna(method='pad')

# this is warnings and the meaning of this warning is in future we will remove or update this method
# to remove this warning use : import warnings
#                              warnings.filterwarnings('ignore')

# Now

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1904\196241153.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad')


Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0  Pune
3  Satish  27.0   Hyd

In [22]:
df.fillna(method='pad')

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_18972\196241153.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad')


Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0  Pune
3  Satish  27.0   Hyd

In [23]:
df.fillna(method='bfill')

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_18972\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')


Names   Age  City
0  Ramesh  22.0  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   Hyd
3     NaN  27.0   Hyd

In [24]:
df.fillna(method='ffill')

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_18972\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0  Pune
3  Satish  27.0   Hyd

In [25]:
df.fillna(method='nfill')

ValueError: Invalid fill method. Expecting pad (ffill) or backfill (bfill). Got nfill

In [5]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad')
# here when we use pad method output me 
# jaha jaha bhi null values hai vaha vaha uske uppar ki value print ho jayenge
# and agar null value ke upar koi value nahi hai to vaha pr null hi rahega

Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0  Pune
3  Satish  27.0   Hyd

In [30]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad',axis=1)

Names     Age  City
0  Ramesh  Ramesh  Pune
1  Suresh    22.0  Pune
2  Satish    25.0  25.0
3     NaN    27.0   Hyd

In [27]:
df.fillna(method='bfill')

Names   Age  City
0  Ramesh  22.0  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   Hyd
3     NaN  27.0   Hyd

In [28]:
df.fillna(method='ffill')

Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0  Pune
3  Satish  27.0   Hyd

In [6]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='nfill')

ValueError: Invalid fill method. Expecting pad (ffill) or backfill (bfill). Got nfill

In [ ]:
# Now instead of filling random values fill with mean,median,mode
# fill kya karna hai?
# => null values

In [33]:
age_mean=df['Age'].mean()
df['Age'].fillna(age_mean)

0    24.666667
1    22.000000
2    25.000000
3    27.000000
Name: Age, dtype: float64

In [34]:
age_mean=df['Age'].mean()
df.fillna(age_mean)

Names        Age       City
0     Ramesh  24.666667       Pune
1     Suresh  22.000000       Pune
2     Satish  25.000000  24.666667
3  24.666667  27.000000        Hyd

In [35]:
age_median=df['Age'].median()
df['Age'].fillna(age_median)

0    25.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [36]:
age_mode=df['Age'].mode()
df['Age'].fillna(age_mode)

0    22.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [38]:
city_median=df['City'].median()
df['City'].fillna(city_median)
# here why error come?
# => beacuse city column jo hai  ussme categorical values hai na ki numerical 

TypeError: Cannot convert ['Pune' 'Pune' nan 'Hyd'] to numeric

In [39]:
city_mode=df['City'].mode()
df['City'].fillna(city_mode)

0    Pune
1    Pune
2     NaN
3     Hyd
Name: City, dtype: object

In [40]:
city_mean=df['City'].mean()
df['City'].fillna(city_mean)

TypeError: can only concatenate str (not "int") to str

In [41]:
mode=df['City'].mode()
mode

0    Pune
Name: City, dtype: object

In [ ]:
# Searech on youtube how to do KNNImputer, It is not teach by sir very well

What is KNN Imputer?
KNN Imputer in Machine Learning (K-Nearest Neighbors) KNN Imputer is a machine learning algorithm 
that can help you fill in the blanks in your data.
It does this by finding the most similar data points to the one with the missing value 
and then using the average of those values to fill in the missing value.

**KNN Immputer**

- K - means any number

- NN - So NN means Nearest Neighbours

-  Where k = hyper parameter which means user can change

- In machine learing there are two things

- 1) parameter  2) Hyper parameter

- 1) parameter means model will update the value internally
 
  2) hyper parameter means user will change it by their will
 
            def(a,b):
               return(a+b)
                    
            add(10,20)
            
         # Here 10,20 is hyper parameter and if we want to change we can change it        

 
-  Idea: Instead of taking all the sample average

      - first fix the neighbours number i.e. k
 
      - Then find the neighbours using distance matric
 
      - Then take the average of those samples to fill the missing values

In [1]:
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer


In [7]:
import numpy as np 
import pandas as pd
from sklearn.impute import KNNImputer
x=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(x)
imputer = KNNImputer(n_neighbors=2,
                    weights='uniform')

imputer.fit_transform(x)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [ ]:
# Here missing value analysis is done 

In [ ]:
# Now there is one more session is there which is transformation
# It is a optional session do it by your own 
# sir explain it bit, rest part search on google 
# Note: ye vahi transformation hai jo humane statistics me dekhe the 
# jaisake ki log transformation,reciprocal transformation 

In [ ]:
==============================EDA Steps==========================================


1. Read the data

2. Separate categorical columns and Numerical Columns

3. Data quick checks shape, columns, dtypes,

4. Null value analysis

A) Check if any Null values are present

B) Fill the null values with Median or KNNImputer for Numerical Columns

C) Fill the null values with Mode for categorical columns

5. Do some data preprocess if any column is corrupted

ex: Numerical values in categorical columns

ex: Categorical values in numerical columns

6. Drop the Id type columns which means a Data has more unique labels 

Drop the Single value columns

7. Categorical column analysis

A) Frequency table

B) Bar charts

C) Pie charts

8. Numerical Column analysis

A) Histogram

B) Distribution

C) Box plot

9. Outlier analysis Impute the outliers with Median

10. Find the Correlation between numerical columns Heat map

11. Convert cat to Numerical

A) LabelEncoder

B) One hot encoder

12. Scale the data

A) Z standardization

B) Normalization

by the time of 12 steps, we achieve 3 things

(i) Cleaned data

(ii) Data in the form of complete Numerical

(iii) we have some understanding the data

13. we will try to select the important feature For ML model

A) PCA: principle component analysis (will be covered in ML)

Finally we achieve 3 data sets

Class

1. Till step-11

with out scale but data in Numerical format